### ISSUE TITLE
Keep being awesome

### ISSUE THREAD

**Issue by ar4s-eth** [web3os-org/kernel#2]
Sorry, not much to add but awesome to see that with so many web3 projects dying off you're still keeping at it.

**Comment by mathiscode** [comment]
Thank you so much! I believe in what web3 really is (or can be), but it seems like with the whole NFT/Metaverse thing web3 got lumped in and its reputation suffered as a result. This project has even kind of outgrown its web3 name and become its own web-based OS capable of integrating with modern (and experimental) browser APIs.

I'm hoping some talented developers will find this project interesting and take it to new heights! 😁
