### ISSUE TITLE
BrowserFS deprecated

### ISSUE THREAD

**Issue by james-pre** [web3os-org/kernel#8]
Hi @mathiscode, I'm a maintainer of BrowserFS. I've been going through the forks of browserfs.

Please see the notice in the readme: https://github.com/jvilk/browserfs

Would you be interested in updating your project to use the updated fork, [ZenFS](https://github.com/zen-fs/core)?

I've created the issue on this repository since I am unable to create an issue on your fork of BrowserFS, [web3os-org/BrowserFS](https://github.com/web3os-org/BrowserFS).

**Comment by mathiscode** [comment]
@dr-vortex thank you for letting me know about the updated fork! I hadn't heard about it, and one of the reasons development on web3os stalled a bit was due to lingering issues in old versions of BrowserFS. ZenFS looks like exactly what I needed when I started this project - great work!

I'll leave this issue open to track progress of the upgrade to ZenFS as time permits. I hope I can contribute to ZenFS along the way as well!

**Comment by dr-vortex** [comment]
@mathiscode,

I'm glad I can help! Please let me know if you experience any issues or if there is any features you would like added.

**Comment by james-pre** [comment]
@mathiscode  I've updated my GitHub username from @dr-vortex to @james-pre. Please update your comment, and I can delete this one. I'm writing this comment when I can't make the change myself.

**Comment by roninjin10** [comment]
@mathiscode I was thinking it might be worth migrating to web containers https://webcontainers.io/ but I don't feel super strongly about that. I was independently looking into ZenFS as well

**Comment by james-pre** [comment]
Hey @mathiscode, just to let you know, `@zenfs/core` 1.0.0 is out.

**Comment by mathiscode** [comment]
Thanks @james-pre! I'm actually rewriting everything from the ground up and the new project is currently using `@zenfs/core` 1.0.2. I see I'm already a few releases behind - great work!

I've had the opportunity to dig more deeply into the zenfs code and I have to say I'm a fan. You really did a great job with it, and I hope to submit contributions soon! You made BrowserFS what it should have been.

I'll reach out personally when the new codebase is released in case you want to play with it!

**Comment by james-pre** [comment]
@mathiscode,

Thank you for the compliments and for the interest in the project. It's nice to see so much positivity around the project.

In case it piques your curiosity, I am working on adding devices and device files, which I think will allow users of ZenFS to do some really creative things.

**Comment by mathiscode** [comment]
That would go perfectly with the `devices` feature of the new kernel! Right now, /dev/ files are just regular text files with metadata that the kernel interprets. Looking forward to seeing your results!

**Comment by roninjin10** [comment]
Sorry for the dumb question but what is a device file?

**Comment by james-pre** [comment]
@roninjin10 You may find [this](https://wikipedia.org/wiki/Device_file) article to be useful.

**Comment by mathiscode** [comment]
@james-pre @roninjin10 

The web3os successor is finally ready to preview! It's called ecmaOS - here are all the relevant links:

https://ecmaos.sh
https://docs.ecmaos.sh
https://github.com/ecmaos/ecmaos
https://www.youtube.com/watch?v=WOsbRim0b6E

Let me know what you think so far!

**Comment by roninjin10** [comment]
Very cool stuff!  Congrats on launching
